### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by ewnd9** [ewnd9/dotfiles#1]
## awesome

- [x] change `meta+shift+{1-9}` to also open a tag with moving active window to the tag https://github.com/ewnd9/dotfiles/commit/68e88fde4e49571dbb4f314a36634f34edd1dd23
- [x] replace `startup.lua` with `.xinitrc` [reddit-thread](https://www.reddit.com/r/awesomewm/comments/4c579v/should_i_starts_other_apps_in_rclua_or_xinitrc/) https://github.com/ewnd9/dotfiles/commit/3523b73e4a8b77b81dcc468b2fb23075359842c7

## tmux

- [x] copy to the clipboard https://github.com/tmux-plugins/tmux-yank https://github.com/ewnd9/dotfiles/commit/07bb41abbb045cfef7a58783f36695992d3dfdc5

## zsh

- [x] fish like autocompletion https://github.com/zsh-users/zsh-completions [[demo](https://cloud.githubusercontent.com/assets/1713789/13947312/c533c4fc-f054-11e5-8d41-e4ca4c28f89e.gif)]

## atom

- [x] open a directory which contains a file in terminal from the file tree [`atom-open-terminal-here`](https://github.com/blueimp/atom-open-terminal-here) https://github.com/ewnd9/dotfiles/commit/bf9df42d2ed743efd4a3deb4e333e4c1645a4076

## vim

- [x] port snippets from atom https://github.com/ewnd9/dotfiles/commit/fa57210effb548c7af567a18e6ed1b30c16c1fcc
